### ISSUE TITLE
Use of [unowned self] causing occasional crashing

### ISSUE THREAD

**Issue by repomies** [audienceproject/userreport-ios-sdk#17]
Our crash logs are showing a couple of production crashes in UserReport.swift with a `.failure` result from `getConfig`:
```
5  libswiftCore.dylib             0x1a0bb0ea4 swift_unknownObjectUnownedTakeStrong + 70
6  UserReport                     0x102982f8c closure #2 in UserReport.init(sakId:mediaId:user:settings:anonymousTracking:) + 259 (UserReport.swift:259)
```

Using `weak self` might be enough to fix this.

**Comment by pyrtsa** [comment]
There indeed seems to be a race condition in the network callbacks of `UserReport.init(sakId:mediaId:user:settings:anonymousTracking:)`.

The callback closures (of which the crash happened in the second one) are executed on the URLSession's background queue (labelled e.g. "Thread 14 Queue : com.apple.NSURLSession-delegate (serial)"). But inside these closures, several shared mutable variables are assigned without proper synchronisation around all of their reads and writes, throughout the SDK.

I think the easiest fix would be to just move all SDK logic back to the main thread, but then UserReport SDK won't be thread safe but must be used from the main thread only.

**Comment by pyrtsa** [comment]
That said, @repomies is probably also right in that `unowned self` is the wrong capture here and `weak self` – or even just a strong, short-lived retain cycle – would both avoid the reported crash.

**Comment by hmvs** [comment]
Thank you for the report we will take a look at it.

**Comment by hmvs** [comment]
We've released the [2.0.1](https://github.com/audienceproject/userreport-ios-sdk/releases/tag/2.0.1) version with the fix. Thank you for the report.

**Comment by pyrtsa** [comment]
Thanks for the fix!

Will you also look into the threading issues at some point?

**Comment by hmvs** [comment]
Yes, we will. Thank you guys for the report.
