### ISSUE TITLE
iOS 9 support

### ISSUE THREAD

**Issue by Fjalmari** [audienceproject/userreport-ios-sdk#3]
I noticed from changelog that iOS 9 support was dropped in version 0.0.8.
Here is the reason for dropping the support:
https://github.com/audienceproject/userreport-ios-sdk/blob/master/UserReport/UserReport/UI/SurveyViewController.swift#L140

I think it would be more convenient to add availability check and use [old way](https://developer.apple.com/documentation/uikit/uiapplication/1622961-openurl) for iOS 9.

**Comment by hmvs** [comment]
Hi @Fjalmari. 

Are you targeting iOS 9? Have you checked what is the percentage of the traffic comes from iOS 9? 
We've dropped it because it seems that it is not used pretty match already.

Numbers:
https://developer.apple.com/support/app-store/
https://david-smith.org/iosversionstats/

**Comment by hmvs** [comment]
support of iOS 9.0 is implemented. #8
